server:
  port: 9003
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EPLOYEE-SERVICE
          uri: lb://EPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost